---

# Notes:
# Sample project C code is not presently written to produce a release artifact.
# As such, release build options are disabled.
# This sample, therefore, only demonstrates running a collection of unit tests.

:project:
  :use_exceptions: FALSE
  :use_test_preprocessor: TRUE
  :use_auxiliary_dependencies: TRUE
  :build_root: build
  :which_ceedling: ../../third-party/ceedling
  # :release_build: TRUE
  :test_file_prefix: test_
  :options_paths: 
    - ../../tools/ceedling

#:release_build:
#  :output: TempSensor.out
#  :use_assembly: FALSE

:environment: []

:extension:
  :executable: .out

:paths:
  :test:
    - +:test/**
    - -:test/support
  :source:
    - src/**
  :include:
    - inc/**
    - ../moduleB/inc/**
  :support:
    - test/support

:defines:
  :common: &common_defines []
  :test:
    - *common_defines
    - TEST
  :test_preprocess:
    - *common_defines
    - TEST

:cmock:
  :when_no_prototypes: :warn
  :plugins: [ignore_arg, ignore, callback]
  :mock_prefix: Mock_
  :callback_after_arg_check: TRUE
  :when_ptr: :compare_ptr
  :enforce_strict_ordering: TRUE
  :treat_as:
    uint8:    HEX8
    uint16:   HEX16
    uint32:   UINT32
    int8:     INT8
    bool:     UINT8

#:tools:
# Ceedling defaults to using gcc for compiling, linking, etc.
# As [:tools] is blank, gcc will be used (so long as it's in your system path)
# See documentation to configure a given toolchain for use

:tools_test_linker:
  :arguments:
    - -lm
:tools_gcov_linker:
  :arguments:
    - -lm

:gcov:
  :html_report_type: detailed

:module_generator:
  :inc_root: inc/

:plugins:
#:load_paths:
#    - ../../third-party/ceedling/plugins
  :enabled:
    - stdout_pretty_tests_report
    - module_generator
    - gcov

